'use strict';
const assert = require('node:assert/strict');
const F = require('../core/dev-file-workflow');
const prep = '用 project-prep 整理当前仓库，接入 AI HUB 群聊开发，保留现有测试和合并规则。';
assert.equal(F.appendProjectPrep(''), prep);
const draft = '  用户任务\n保留多行和空格  \n';
assert.equal(F.appendProjectPrep(draft), draft + '\n\n' + prep);
assert.equal(F.appendProjectPrep(F.appendProjectPrep(draft)), F.appendProjectPrep(draft));
assert.equal(F.appendProjectPrep(prep + '\n后续补充'), prep + '\n后续补充');
const scan = (...names) => F.fromNames(names);
assert.equal(scan().phase, 'discuss');
assert.equal(scan('开题报告.md').phase, 'kickoff');
assert.equal(scan('已完成-开题报告.md').key, 'build:1');
assert.equal(scan('已完成-开题报告.md', '实现手册-轮次1.md').draftExists, true);
assert.equal(scan('已完成-开题报告.md', '已完成-实现手册-轮次1.md').key, 'merge:1');
const review = ['已完成-开题报告.md', '已完成-实现手册-轮次1.md'];
assert.equal(scan(...review, '需返工-合并手册-轮次1.md').key, 'build:2');
assert.equal(scan(...review, '已完成-合并手册-轮次1.md').done, true);
assert(scan(...review, '合并手册-轮次1.md', '已完成-合并手册-轮次1.md').error);
assert(scan('已完成-实现手册-轮次1.md').error);
assert(scan(...review, '已完成-合并手册-轮次1.md', '实现手册-轮次2.md').error);
assert.equal(scan('阶段1合并手册.md', 'unrelated.md').phase, 'discuss');
let chain = ['已完成-开题报告.md'];
for (let n = 1; n <= 11; n++) chain.push(`已完成-实现手册-轮次${n}.md`, `需返工-合并手册-轮次${n}.md`);
assert.equal(F.fromNames(chain.reverse()).round, 12);
assert(F.isResume('继续')); assert(F.isResume('继续执行，按刚才的要求'));
assert(!F.isResume('现在进展如何')); assert(!F.isResume('不要继续')); assert(!F.isResume('继续是什么意思？'));
const preset = F.appendKickoff('用户原始任务\n保留这一行', 'preset one');
assert.equal(F.appendKickoff(preset + '\n补充要求', 'preset two'), '用户原始任务\n保留这一行\n补充要求\n\n' + F.PRESET_START + '\npreset two\n' + F.PRESET_END);
console.log('dev-file-workflow: filename chain, conflicts, numeric rounds, resume and prefill passed');
