'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const {buildAcpOptions,PLAN_BASE_URL}=require('../core/acp-profiles');
const {imagePaths,validateImages}=require('../core/acp-attachments');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'hub-acp-profile-'));
const entry=path.join(root,'cli.js');fs.writeFileSync(entry,'');
const config={acp:{nodePath:process.execPath,apiKey:'test-private-credential',providers:{qwen:{entryPath:entry,model:'qwen3.8-max'}}}};
const options={id:'one',cwd:root};
const built=buildAcpOptions('qwen',options,config,root,{ZCODE_ACP_RESUME_SESSION:'foreign',DSH_HOME:'foreign',CODEX_HOME:'foreign',OPENAI_API_KEY:'foreign',ANTHROPIC_AUTH_TOKEN:'foreign',NODE_OPTIONS:'foreign',PATH:process.env.PATH});
assert.equal(built.launch.env.OPENAI_BASE_URL,PLAN_BASE_URL);assert.equal(built.launch.env.OPENAI_API_KEY,config.acp.apiKey);
assert.equal(built.launch.env.USERPROFILE,built.home);assert.equal(built.launch.env.PATH,process.env.PATH);
for(const key of ['ZCODE_ACP_RESUME_SESSION','DSH_HOME','CODEX_HOME','ANTHROPIC_AUTH_TOKEN','NODE_OPTIONS'])assert.equal(built.launch.env[key],undefined);
assert(!built.launch.args.join(' ').includes(config.acp.apiKey));
assert.throws(()=>buildAcpOptions('qwen',options,{acp:{...config.acp,baseURL:'https://api.deepseek.com/v1'}},root),/端点/);
assert.throws(()=>buildAcpOptions('qwen',{...options,model:'deepseek-official::deepseek-v4-pro'},config,root),/命名空间/);
const mcp=path.join(root,'mcp.json');fs.writeFileSync(mcp,JSON.stringify([{name:'tool',command:'node',args:['server.js'],env:[]}]));
config.acp.providers.qwen.mcpConfigPath=mcp;
assert.equal(buildAcpOptions('qwen',options,config,root).mcpServers[0].name,'tool');
fs.writeFileSync(mcp,'{}');assert.throws(()=>buildAcpOptions('qwen',options,config,root),/数组/);
delete config.acp.providers.qwen.mcpConfigPath;
const outside=fs.mkdtempSync(path.join(os.tmpdir(),'hub-acp-foreign-'));
assert.throws(()=>buildAcpOptions('qwen',{id:'branch',cwd:root,acpFork:{home:outside}},config,root),/分叉目录/);
const file=path.join(root,'sample with spaces.png');fs.writeFileSync(file,Buffer.alloc(16));
assert.deepEqual(imagePaths('看看 "'+file+'"\n"'+file+'"'),[{type:'localImage',path:file}]);
assert.throws(()=>validateImages(imagePaths('"'+file+'"'),'glm-5.2',{promptCapabilities:{image:true}}),/不支持图片/);
assert.throws(()=>validateImages(Array(5).fill({type:'localImage',path:file}),'qwen3.8-max',{promptCapabilities:{image:true}}),/最多/);
assert.doesNotThrow(()=>validateImages([{type:'localImage',path:file}],'qwen3.8-max',{promptCapabilities:{image:true}}));
console.log('ACP profiles: route lock, environment isolation, MCP validation, fork containment and image capabilities PASS');
