'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {AssistantService}=require('../core/hub-assistant/service');
const {AssistantStore}=require('../core/hub-assistant/store');
const {AssistantWatches}=require('../core/hub-assistant/watches');
const {readFinals,LiveHistory}=require('../core/hub-assistant/live-history');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'assistant-live-')),file=path.join(dir,'native.jsonl');
 const meta={id:'target-original',kind:'codex',title:'订单同步验收',codexSid:'native-exact',transcriptPath:file,status:'idle'};
 const append=row=>fs.appendFileSync(file,JSON.stringify(row)+'\n','utf8');append({type:'session_meta',payload:{id:meta.codexSid,source:'cli'}});
 const final=(text,turn='t1',at=Date.now())=>{append({timestamp:new Date(at).toISOString(),type:'event_msg',payload:{type:'task_started',turn_id:turn}});append({timestamp:new Date(at).toISOString(),type:'response_item',payload:{type:'message',role:'assistant',phase:'final_answer',content:[{type:'output_text',text}]}});};
 const store=new AssistantStore(dir),notices=[];const watches=new AssistantWatches(store,{getSession:()=>meta,onNotification:n=>notices.push(n)});t.after(()=>{try{store.close();}catch{}});return{dir,file,meta,append,final,store,watches,notices};}
test('real Codex final_answer phase is read; partial/tool/completion-only records are not reply text',t=>{const x=setup(t);x.final('已从7项推进到8项');
 x.append({type:'response_item',payload:{type:'message',role:'assistant',phase:'commentary',content:[{type:'output_text',text:'部分内容'}]}});
 x.append({type:'event_msg',payload:{type:'task_complete',last_agent_message:'不能用完成事件合成正文'}});
 assert.deepEqual(readFinals(x.meta).records.map(r=>r.text),['已从7项推进到8项']);
 assert.equal(readFinals({...x.meta,codexSid:'wrong'}).available,false);
});
test('watch excludes baseline replies, persists notifications and deduplicates the same turn/message',t=>{const x=setup(t);x.final('旧答','old');x.watches.follow(x.meta.id);assert.equal(x.watches.poll().notifications.length,0);
 x.final('新答','new');x.watches.poll();x.watches.poll();assert.equal(x.notices.length,1);
 const item=x.watches.notifications().notifications[0];assert.equal(item.text,'新答');assert.equal(item.source.turnId,'new');
 x.watches.markRead(item.id);assert.equal(x.watches.notifications().unreadCount,0);
 const second=new AssistantWatches(x.store,{getSession:()=>x.meta});assert.equal(second.poll().notifications.length,1);
});
test('restart resumes persisted cursor and captures replies written while Hub was closed',t=>{const x=setup(t);x.final('基线','old');x.watches.follow(x.meta.id);x.store.close();x.final('离线期间的新回复','offline');
 const store=new AssistantStore(x.dir);t.after(()=>store.close());const next=new AssistantWatches(store,{getSession:()=>x.meta});assert.equal(next.poll().notifications[0].text,'离线期间的新回复');assert.equal(next.poll().notifications.length,1);
});
test('partial JSON final is only notified after a complete newline-terminated record',t=>{const x=setup(t);x.watches.follow(x.meta.id);const row=JSON.stringify({timestamp:new Date().toISOString(),type:'response_item',payload:{type:'message',role:'assistant',phase:'final_answer',id:'message-one',content:[{type:'output_text',text:'完整了'}]}});
 fs.appendFileSync(x.file,row.slice(0,100));assert.equal(x.watches.poll().unreadCount,0);fs.appendFileSync(x.file,row.slice(100)+'\n');assert.equal(x.watches.poll().unreadCount,1);
});
test('native identity changes suspend watch rather than accepting another target',t=>{const x=setup(t);x.watches.follow(x.meta.id);x.meta.codexSid='other';x.final('错会话');assert.equal(x.watches.poll().unreadCount,0);assert.equal(x.watches.list()[0].state,'error');});
test('a repeated final from the same native turn is notified once even if its text changed',t=>{const x=setup(t);x.watches.follow(x.meta.id);x.final('第一次最终答复','same-turn');x.watches.poll();x.final('同一轮最终答复格式改变','same-turn');assert.equal(x.watches.poll().notifications.length,1);assert.equal(x.notices.length,1);});
test('huge rejected tool rows do not trap a watch cursor before the next final answer',t=>{const x=setup(t);let cursor=readFinals(x.meta).cursor;x.append({type:'response_item',payload:{type:'function_call_output',output:'x'.repeat(3000)}});x.final('工具之后的最终答复','after-tool');const records=[];
 for(let i=0;i<15;i++){const result=readFinals(x.meta,{cursor,maxReadBytes:512});records.push(...result.records);cursor=result.cursor;if(!result.backlog)break;}
 assert.deepEqual(records.map(r=>r.text),['工具之后的最终答复']);
});
test('Claude requires exact file identity and explicit end_turn assistant body',t=>{const x=setup(t);fs.writeFileSync(x.file,'');const meta={...x.meta,kind:'claude',ccSessionId:'claude-exact'};
 x.append({type:'user',uuid:'user1',sessionId:meta.ccSessionId,message:{role:'user',content:'任务'}});
 x.append({type:'assistant',uuid:'a1',sessionId:meta.ccSessionId,message:{id:'m1',stop_reason:'tool_use',content:[{type:'text',text:'过程'}]}});
 x.append({type:'assistant',uuid:'a2',timestamp:new Date().toISOString(),sessionId:meta.ccSessionId,message:{id:'m2',stop_reason:'end_turn',content:[{type:'text',text:'最终原文'}]}});
 assert.deepEqual(readFinals(meta).records.map(r=>r.text),['最终原文']);assert.equal(readFinals({...meta,ccSessionId:'other'}).available,false);
});
test('all 20 open sessions have latest final evidence, independent of historical index capacity',t=>{const x=setup(t);x.final('当前最终结果');const sessions=Array.from({length:20},(_,i)=>({...x.meta,id:'s'+i,title:'任务'+i}));const service=new AssistantService({dataDir:path.join(x.dir,'hub'),getSession:id=>sessions.find(s=>s.id===id),getAllSessions:()=>sessions});t.after(()=>service.close());
 const inventory=service.liveInventory();assert.equal(inventory.length,20);assert.equal(inventory.filter(s=>s.latestFinal?.text==='当前最终结果').length,20);
});
test('closed target resumes its original native identity and sends only once',async t=>{const x=setup(t);let opened=null,resumed=0,sent=0;const service=new AssistantService({dataDir:path.join(x.dir,'hub'),getSession:()=>opened,getSessionMetadata:()=>x.meta,listKnownSessions:()=>[x.meta],getAllSessions:()=>opened?[opened]:[],resumeSession:async id=>{assert.equal(id,x.meta.id);resumed++;opened={...x.meta};return opened;},sendPrompt:async id=>{assert.equal(id,x.meta.id);sent++;return{ok:true,receipt:{status:'confirmed'}};}});t.after(()=>service.close());
 const action={type:'send',targetSessionId:x.meta.id,text:'推进到8项',requestId:'original-restore-1'};assert.equal((await service.execute(action)).state,'acknowledged');await service.execute(action);assert.equal(resumed,1);assert.equal(sent,1);
});
test('failed or wrong-identity resume never launches a replacement or dispatches',async t=>{const x=setup(t);let sent=0,opened=null;const service=new AssistantService({dataDir:path.join(x.dir,'hub'),getSession:()=>opened,getSessionMetadata:()=>x.meta,getAllSessions:()=>[],resumeSession:async()=>{opened={...x.meta,codexSid:'other'};},sendPrompt:async()=>{sent++;}});t.after(()=>service.close());
 const result=await service.execute({type:'send',targetSessionId:x.meta.id,text:'推进',requestId:'original-restore-2'});assert.equal(result.state,'unknown');assert.match(result.error,/身份未确认/);assert.equal(sent,0);
});
test('late confirmation reconciles only its exact action and target without resending',async t=>{const x=setup(t);let sent=0;const service=new AssistantService({dataDir:path.join(x.dir,'hub'),getSession:()=>x.meta,getAllSessions:()=>[x.meta],sendPrompt:async()=>{sent++;return{ok:true,receipt:{status:'unconfirmed'}};}});t.after(()=>service.close());
 const action={type:'send',targetSessionId:x.meta.id,text:'推进',requestId:'late-receipt-001'};assert.equal((await service.execute(action)).state,'unknown');
 assert.equal(service.observePromptReceipt({status:'confirmed',clientSubmissionId:action.requestId,sessionId:'wrong'}),false);
 assert.equal(service.observePromptReceipt({status:'confirmed',clientSubmissionId:'another-id',sessionId:x.meta.id}),false);
 assert.equal(service.observePromptReceipt({status:'confirmed',clientSubmissionId:action.requestId,sessionId:x.meta.id}),true);
 const duplicate=await service.execute(action);assert.equal(duplicate.state,'acknowledged');assert.equal(duplicate.result.originalReceipt.receipt.status,'unconfirmed');assert.equal(sent,1);
});
test('explicit send plus reminder creates the baseline before a fast reply arrives',async t=>{const x=setup(t);x.final('旧答','old');const service=new AssistantService({dataDir:path.join(x.dir,'hub'),getSession:id=>id===x.meta.id?x.meta:null,getAllSessions:()=>[x.meta],sendPrompt:async()=>{x.final('本轮新答','new');return{ok:true,receipt:{status:'confirmed'}};}});t.after(()=>service.close());
 service.preparePrompt({text:'推进订单同步，回复后第一时间反馈'});await service.invokeTool({name:'send_session',arguments:{sessionId:x.meta.id,text:'推进',operationKey:'one',requestToken:service.currentRequest.token}});
 assert.equal(service.pollWatches().notifications[0].text,'本轮新答');assert.equal(service.notifications().notifications.length,1);
});
test('watch shorthand requires a unique named target and explicit reminder intent',async t=>{const x=setup(t);const service=new AssistantService({dataDir:path.join(x.dir,'hub'),getSession:id=>id===x.meta.id?x.meta:null,getAllSessions:()=>[x.meta]});t.after(()=>service.close());
 service.preparePrompt({text:'订单同步有回复就提醒我'});assert.equal((await service.invokeTool({name:'watch_session',arguments:{sessionId:x.meta.id,requestToken:service.currentRequest.token}})).ok,true);
 service.preparePrompt({text:'订单同步现在什么情况'});await assert.rejects(service.invokeTool({name:'watch_session',arguments:{sessionId:x.meta.id,requestToken:service.currentRequest.token}}),/没有明确/);
});
test('only the Hub holding the assistant entity runs its scheduled reconciliation',t=>{const x=setup(t),dataDir=path.join(x.dir,'hub');let held=true,ownerPolls=0,otherPolls=0;
 const owner=new AssistantService({dataDir,getSession:id=>held&&id==='assistant-owner'?{id}:null,getAllSessions:()=>[]});const other=new AssistantService({dataDir,getSession:()=>null,getAllSessions:()=>[]});t.after(()=>{owner.close();other.close();});
 owner.store.set('sessionId','assistant-owner');owner.pollWatches=()=>{ownerPolls++;};other.pollWatches=()=>{otherPolls++;};owner.maybeRotateInBackground=other.maybeRotateInBackground=async()=>null;
 t.mock.timers.enable({apis:['setInterval','setTimeout']});owner.startWatching({reconcileMs:500,startupDelayMs:100000});other.startWatching({reconcileMs:500,startupDelayMs:100000});t.mock.timers.tick(500);assert.equal(ownerPolls,1);assert.equal(otherPolls,0);held=false;t.mock.timers.tick(500);assert.equal(ownerPolls,1);assert.equal(otherPolls,0);
});
test('latest final survives large later tool output in incremental reads and a cold reader',t=>{const x=setup(t);x.final('7项已完成，等待第8项决策','original-turn');const reader=new LiveHistory(),original=reader.read(x.meta).records.at(-1);
 x.append({type:'response_item',payload:{type:'function_call_output',output:'工具输出'.repeat(350000)}});
 assert.equal(reader.read(x.meta).records.at(-1).text,original.text);
 const cold=new LiveHistory().read(x.meta).records.at(-1);assert.equal(cold.text,original.text);assert.equal(cold.turnId,original.turnId);assert.equal(cold.ref,original.ref);
 x.final('已经推进到8项','new-turn');assert.equal(reader.read(x.meta).records.at(-1).text,'已经推进到8项');
});
test('closed and other-Hub targets pause tracking, keep cursor, and catch up only after local resume',t=>{const x=setup(t);let opened=true;const watcher=new AssistantWatches(x.store,{getSession:()=>x.meta,getOpenSession:()=>opened?x.meta:null});
 x.final('关注前旧答','old');watcher.follow(x.meta.id);const baseline=watcher.list()[0].cursor;opened=false;x.final('其他Hub打开后产生的答复','remote');
 assert.equal(watcher.poll().notifications.length,0);assert.equal(watcher.list()[0].state,'paused-closed');assert.deepEqual(watcher.list()[0].cursor,baseline);
 opened=true;assert.equal(watcher.poll().notifications[0].text,'其他Hub打开后产生的答复');assert.equal(watcher.poll().notifications.length,1);
});
test('concurrent duplicate dispatch reserves its ledger before awaiting original-session resume',async t=>{const x=setup(t);let opened=null,resumed=0,sent=0,release;const gate=new Promise(resolve=>{release=resolve;});const service=new AssistantService({dataDir:path.join(x.dir,'hub'),getSession:()=>opened,getSessionMetadata:()=>x.meta,getAllSessions:()=>[],resumeSession:async()=>{resumed++;await gate;opened={...x.meta};},sendPrompt:async()=>{sent++;return{ok:true,receipt:{status:'confirmed'}};}});t.after(()=>service.close());
 const action={type:'send',targetSessionId:x.meta.id,text:'推进',requestId:'concurrent-resume-1'};const first=service.execute(action),second=await service.execute(action);assert.equal(resumed,1);assert.equal(second.duplicate,true);release();assert.equal((await first).state,'acknowledged');assert.equal(sent,1);
});
test('failed resume remains unknown and a duplicate never retries restoration',async t=>{const x=setup(t);let resumed=0;const service=new AssistantService({dataDir:path.join(x.dir,'hub'),getSession:()=>null,getSessionMetadata:()=>x.meta,getAllSessions:()=>[],resumeSession:async()=>{resumed++;throw new Error('lost resume response');}});t.after(()=>service.close());
 const action={type:'send',targetSessionId:x.meta.id,text:'推进',requestId:'failed-resume-123'};assert.equal((await service.execute(action)).state,'unknown');assert.equal((await service.execute(action)).needsReconciliation,true);assert.equal(resumed,1);
});
