'use strict';
const assert=require('assert/strict');
const store=new Map();
global.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const journal=require('../renderer/groupchat-journal');
const meeting={id:'g1'};
const msg={sid:'same-provider-1',turnNum:3,id:'pending-1'};
const a=journal.attributes(meeting,msg,escapeHtml);
const b=journal.attributes(meeting,{...msg,id:'durable-1'},escapeHtml);
assert.equal(a,b,'pending and durable answer keep the same reading identity');
assert.notEqual(a,journal.attributes(meeting,{...msg,turnNum:4},escapeHtml),'a new round must not reuse disclosure');
assert.notEqual(journal.attributes(meeting,{...msg,sourceMessage:'progress-1'},escapeHtml),journal.attributes(meeting,{...msg,sourceMessage:'final-1'},escapeHtml),'legacy native source cards keep independent disclosure');
assert.notEqual(journal.attributes(meeting,{...msg,committeeAct:'辩论',committeeRound:1},escapeHtml),journal.attributes(meeting,{...msg,committeeAct:'辩论',committeeRound:2},escapeHtml),'committee rounds keep independent disclosure');
const palette=[1,2,3,4,5,6].map(i=>journal.attributes(meeting,{...msg,sid:'same-provider-'+i},escapeHtml).match(/data-journal-color="(\d+)"/)[1]);
assert.equal(new Set(palette).size,6,'members of the same provider must be distinguishable');
const reordered=journal.attributes(meeting,msg,escapeHtml);
assert.equal(a,reordered,'new members do not recolor existing ones');
const id=JSON.stringify(['saved','member',1,'']);
store.set('gc-journal:'+id,JSON.stringify({expanded:true,minimized:true}));
const saved=journal.attributes({id:'saved'},{sid:'member',turnNum:1},escapeHtml);
assert(saved.includes('data-journal-expanded="true"')&&saved.includes('data-journal-minimized="true"'));
store.set('gc-journal-colors:bad','{}');
assert(journal.attributes({id:'bad'},msg,escapeHtml).includes('data-journal-color="0"'),'invalid cosmetic preference shape must be recoverable');
const view=require('../renderer/conversation-message-view');
const raw=Array.from({length:40},(_,i)=>'第'+i+'行，保留完整内容。').join('\n');
const options={escapeHtml,renderMarkdown:s=>'<p>'+escapeHtml(s)+'</p>'};
assert(view.renderMessageBody(raw,options).includes('conversation-long-message'),'ordinary source-message folding remains enabled');
const native=view.renderMessageSequence([{id:'p',phase:'commentary',text:raw},{id:'f',phase:'final_answer',text:raw}],{...options,foldLong:false});
assert(!native.includes('conversation-long-message'),'group card owns one disclosure, with no nested full-text fold');
assert.equal((native.match(/第39行/g)||[]).length,2,'both source messages remain complete and rendered exactly once');
assert(native.includes('data-message-id="p"')&&native.includes('data-message-id="f"'),'native source boundaries remain intact');
delete global.localStorage;
console.log('groupchat journal: stable identity/palette, saved disclosure, ordinary isolation and complete source rendering PASS');
