'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path');
const {AccountCenter}=require('../core/account-center');
const {createAccountAdapters,quotePS,jsonResult}=require('../core/account-adapters');
const {registerAccountCenterIpc}=require('../main/ipc/account-center-handlers');
function setup(t,overrides={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'hub-accounts-unit-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const config={codexSubscriptionProfiles:[{id:'default',label:'Main',home:path.join(root,'codex')}],deepseekApiKey:'secret-key-DO-NOT-EXPOSE'};const adapter={imageAccounts:async()=>[],check:async()=>({state:'signed_in',identity:'alice@example.com',message:'原生确认',source:'fixture'}),login:async()=>({}),...overrides};const service=new AccountCenter({dataDir:root,homeDir:root,env:{},getConfig:()=>config,adapter});return {root,config,adapter,service};}
test('snapshot keeps credential presence separate from auth and never serializes secrets or homes',async t=>{const {service,root}=setup(t);const s=await service.snapshot();const api=s.connections.find(r=>r.id==='api-deepseek');assert.equal(api.state,'configured');assert.equal(s.connections.find(r=>r.id==='claude').state,'signed_in');assert.equal(s.connections.find(r=>r.id==='claude').identity,'a•••@example.com');assert.ok(!JSON.stringify(s).includes('secret-key'));assert.ok(!JSON.stringify(s).includes(root));assert.equal(s.connections.find(r=>r.id==='bridge').state,'unknown');});
test('two Hub services share one login admission; explicit release permits reopen',async t=>{let count=0;const s=setup(t,{login:async()=>{count++;await new Promise(r=>setTimeout(r,15));return {};}});const second=new AccountCenter({dataDir:s.root,homeDir:s.root,env:{},getConfig:()=>s.config,adapter:s.adapter});await Promise.all([s.service.login('web-deepseek'),second.login('web-deepseek')]);assert.equal(count,1);await second.release('web-deepseek');await s.service.login('web-deepseek');assert.equal(count,2);});
test('failed login releases admission and exposes failure, not success',async t=>{let count=0;const {service}=setup(t,{login:async()=>{count++;throw Error('missing tool');}});await assert.rejects(service.login('bridge'),/无法打开/);await assert.rejects(service.login('bridge'),/无法打开/);assert.equal(count,2);});
test('same account checks coalesce and failures are unknown rather than signed out',async t=>{let count=0;const {service}=setup(t,{check:async()=>{count++;await new Promise(r=>setTimeout(r,15));throw Error('network secret');}});const r=await Promise.allSettled([service.check('bridge'),service.check('bridge')]);assert.equal(count,1);assert.equal(r[0].status,'rejected');const row=(await service.snapshot()).connections.find(r=>r.id==='bridge');assert.equal(row.state,'unknown');assert.ok(!JSON.stringify(service.history()).includes('network secret'));});
test('changing native home or API key cannot inherit a previous identity',async t=>{const {service,config,root}=setup(t);await service.check('codex-default');config.codexSubscriptionProfiles[0].home=path.join(root,'different');assert.equal(service.read(service.scope(service.baseConnections().find(r=>r.id==='codex-default'))),null);await service.check('api-deepseek');config.deepseekApiKey='another';assert.equal(service.read(service.scope(service.baseConnections().find(r=>r.id==='api-deepseek'))),null);});
test('fresh image worker proof replaces queued observation without exposing raw worker results',async t=>{let when=0;const {service}=setup(t,{imageAccounts:async()=>[{id:'primary',state:'signed_in',observedAt:when,enabled:true,workerAlive:true}],check:async()=>({state:'unknown',message:'检查排队中'})});await service.check('image-primary');when=Date.now()+100;const row=(await service.snapshot()).connections.find(r=>r.id==='image-primary');assert.equal(row.state,'signed_in');});
test('unknown connection cannot select filesystem paths or arbitrary login commands',async t=>{const {service}=setup(t);await assert.rejects(service.login('../../secret'),/连接不存在/);await assert.rejects(service.login('api-deepseek'),/接入配置/);});
test('isolated adapter never calls real bridge, image pool or Codex Web GPT',async t=>{const {root}=setup(t);let calls=0;const adapter=createAccountAdapters({dataDir:root,homeDir:root,env:{CLAUDE_HUB_HOME_DIR:root},runImpl:async()=>{calls++;return {};}});await assert.rejects(adapter.imageAccounts(),/隔离/);await assert.rejects(adapter.check({provider:'bridge'}),/隔离/);await assert.rejects(adapter.login({provider:'chatgpt-web'}),/隔离/);assert.equal(calls,0);});
test('Claude official auth JSON is necessary for a positive status',async t=>{const {root}=setup(t);let args;const adapter=createAccountAdapters({dataDir:root,homeDir:root,env:{},runImpl:async(c,a)=>{args=a;return {code:0,stdout:'{"loggedIn":true,"email":"a@example.com"}',stderr:''};}});const result=await adapter.check({provider:'claude',home:root});assert.equal(result.state,'signed_in');assert.deepEqual(args,['auth','status','--json']);const bad=createAccountAdapters({dataDir:root,env:{},runImpl:async()=>({code:0,stdout:'{}'})});await assert.rejects(bad.check({provider:'claude',home:root}),/证据/);});
test('PowerShell literals preserve hostile profile characters and JSON errors propagate',()=>{assert.equal(quotePS("a'$(whoami)"),"'a''$(whoami)'");assert.throws(()=>jsonResult({code:1,stdout:'{"ok":false}'}));assert.deepEqual(jsonResult({code:0,stdout:'noise\n{"ok":true}'}),{ok:true});});
test('IPC converts errors to visible envelopes and validates ids',async()=>{const handlers={};registerAccountCenterIpc({handle:(n,f)=>handlers[n]=f},{snapshot:async()=>({connections:[]}),login:async()=>{throw Error('不可用');}});assert.equal((await handlers['accounts:login']({},{})).ok,false);assert.equal((await handlers['accounts:login']({},{id:'claude'})).error,'不可用');assert.equal((await handlers['accounts:snapshot']({})).ok,true);});
test('an older failing launch cannot release the newer login admission',async t=>{let rejectOld,count=0;const {service}=setup(t,{login:()=>++count===1?new Promise((_,reject)=>{rejectOld=reject;}):Promise.resolve({})});const old=service.login('bridge');while(!rejectOld)await new Promise(r=>setImmediate(r));const failed=assert.rejects(old,/无法打开/);await service.release('bridge');await service.login('bridge');rejectOld(Error('old failure'));await failed;await service.login('bridge');assert.equal(count,2);});
test('server token edits invalidate cached configuration and tilde profiles resolve correctly',async t=>{const {service,config,root}=setup(t);config.operations={aliyunMonitor:{bearerToken:'old'}};await service.check('server-monitor');config.operations.aliyunMonitor.bearerToken='new';assert.equal(service.read(service.scope(service.baseConnections().find(r=>r.id==='server-monitor'))),null);config.codexSubscriptionProfiles[0].home='~/.codex-other';assert.equal(service.baseConnections().find(r=>r.id==='codex-default').home,path.join(root,'.codex-other'));});
test('Feishu user login cannot stand in for the notification bot identity',async t=>{const {root}=setup(t);let args,command;const a=createAccountAdapters({dataDir:root,env:{},getConfig:()=>({notifications:{feishuCliPath:'fixture-cli'}}),runImpl:async(c,v)=>{command=c;args=v;return {code:0,stdout:JSON.stringify({identities:{bot:{available:true},user:{available:false}}})};}});const result=await a.check({provider:'feishu'});assert.equal(result.state,'login_required');assert.match(result.message,/独立机器人身份：已配置/);assert.equal(command,'fixture-cli');assert.deepEqual(args,['auth','status','--json']);});
test('batch validates all ids before launching and skips verified accounts',async t=>{
 let launched=[];const {service}=setup(t,{check:async row=>({state:row.id==='claude'?'signed_in':'unknown'}),login:async row=>{launched.push(row.id);return {stage:'manual',message:'official window'};}});
 await assert.rejects(service.loginMany(['web-doubao','api-deepseek']),/无效/);assert.equal(launched.length,0);
 const b=await service.loginMany(['claude','web-doubao','web-doubao']);while(service.batches.get(b.id).running)await new Promise(r=>setImmediate(r));
 assert.deepEqual(launched,['web-doubao']);assert.equal(service.batches.get(b.id).items[0].stage,'signed_in');
});
test('batch limits concurrency, isolates failures, and never stores the phone',async t=>{
 let active=0,max=0;const phone='13800000000';const {service,root}=setup(t,{check:async()=>({state:'login_required'}),login:async row=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;if(row.id==='web-qwen')throw Error('failed');return {stage:'waiting_code',message:'waiting'};}});
 const b=await service.loginMany(['web-deepseek','web-doubao','web-kimi','web-qwen','web-gemini'],{phone});while(service.batches.get(b.id).running)await new Promise(r=>setTimeout(r,5));
 assert.equal(max,3);assert.equal(service.batches.get(b.id).items.filter(r=>r.stage==='failed').length,1);assert.ok(!JSON.stringify(await service.snapshot()).includes(phone));assert.ok(!fs.readFileSync(path.join(root,'account-center','events.jsonl'),'utf8').includes(phone));
});
test('verification code targets one phone-capable account and is not persisted',async t=>{
 let received;const {service,root}=setup(t,{submitCode:async(row,code)=>{received={id:row.id,code};return {stage:'checking',message:'submitted'};}});
 await assert.rejects(service.submitCode('claude','123456'),/官方窗口/);await service.submitCode('web-doubao','123456');assert.deepEqual(received,{id:'web-doubao',code:'123456'});assert.ok(!JSON.stringify(await service.snapshot()).includes('123456'));
});
test('SMS automation never retries an uncertain mutation',async t=>{
 const {root}=setup(t);let attempts=0;const a=createAccountAdapters({dataDir:root,env:{},browser:{open:async()=>({}),command:async()=>true,preparePhone:async()=>{attempts++;throw Error('disconnected after click');}}});
 const r=await a.login({provider:'doubao',managedBrowser:true,phoneLogin:true},{phone:'13800000000'});assert.equal(attempts,1);assert.equal(r.stage,'manual');
});
test('official phone form yields to CAPTCHA and submits each SMS request only once',()=>{
 const {phoneStep}=require('../core/account-browser'),vm=require('vm');let clicks=0,challenge=false;
 class Input {get value(){return this.current||'';}set value(v){this.current=v;}getClientRects(){return [1];}dispatchEvent(){}}
 const input=new Input();input.placeholder='Phone number';input.dataset={};
 const button={innerText:'Send code',getClientRects:()=>[1],getAttribute:()=>null,click:()=>clicks++};
 const document={querySelector:()=>challenge?{}:null,querySelectorAll:s=>s==='input'?[input]:[button]};
 const run=()=>vm.runInNewContext(`(${phoneStep.toString()})('deepseek','13800000000')`,{document,HTMLInputElement:Input,Event:class{}});
 challenge=true;assert.equal(run().stage,'manual');assert.equal(clicks,0);assert.equal(input.value,'');
 challenge=false;assert.equal(run().stage,'advance');assert.equal(input.value,'13800000000');assert.equal(clicks,0);
 run();assert.equal(clicks,1);run();assert.equal(clicks,1);
});
test('browser checks require provider-page evidence and never infer login from a composer',async t=>{
 const {root}=setup(t),http=require('http'),{WebSocketServer}=require('ws'),{AccountBrowser}=require('../core/account-browser');
 let result={host:'chat.deepseek.com',login:false,profile:false,challenge:false};
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify([{type:'page',url:'https://chat.deepseek.com/',webSocketDebuggerUrl:'ws://127.0.0.1:'+server.address().port+'/page'}]));});
 const wss=new WebSocketServer({server});wss.on('connection',ws=>ws.on('message',data=>{const query=JSON.parse(data);assert.equal(query.method,'Runtime.evaluate');ws.send(JSON.stringify({id:query.id,result:{result:{value:result}}}));}));
 await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{for(const client of wss.clients)client.terminate();await new Promise(r=>wss.close(r));await new Promise(r=>server.close(r));});
 const browser=new AccountBrowser({dataDir:root});fs.mkdirSync(browser.profile('deepseek'),{recursive:true});fs.writeFileSync(path.join(browser.profile('deepseek'),'DevToolsActivePort'),String(server.address().port));
 assert.equal((await browser.check('deepseek')).state,'unknown');result.profile=true;assert.equal((await browser.check('deepseek')).state,'signed_in');
 result.login=true;assert.equal((await browser.check('deepseek')).state,'login_required');result.challenge=true;assert.equal((await browser.check('deepseek')).state,'unknown');
 result.host='other.example';await assert.rejects(browser.check('deepseek'),/页面已切换/);assert.throws(()=>browser.profile('../../arbitrary'),/不支持/);
});
