'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {credentials,seal,open}=require('../core/hub-phone/crypto'),{PhoneChannel}=require('../core/hub-phone/channel');
function harness(){const c=credentials(),s={credentials:c,enabled:true,cursor:0,created:1,inbox:[],outbox:[],notices:[]},calls=[],remote=[];const assistant={switching:false,overview:()=>({status:'idle'}),ensureSession:async()=>({ok:true,sessionId:'fixed-assistant',backendKind:'codex'}),send:async r=>{calls.push(r);return{receipt:{receipt:{status:'confirmed',turnId:'exact-turn'}}}},readLiveFinal:()=>({records:[]}),notifications:()=>({notifications:[]})};const journal={state:s,change:fn=>fn(s)};const channel=new PhoneChannel({assistant,journal,renderCards:async()=>[Buffer.from('image')],transcribe:async()=>'识别内容'});channel.request=async(route,args)=>{if(route==='/poll')return{messages:remote.splice(0)};return{ok:true}};const incoming=(id,value)=>remote.push({seq:remote.length+1,id,payload:seal(c.key,c.channel,id,'phone',value)});return{channel,assistant,s,calls,remote,incoming,c};}
test('AES-GCM authenticates channel, message identity and sender; no plaintext on wire',()=>{const c=credentials(),p=seal(c.key,c.channel,'test-message-123456','phone',{text:'不要创建会话'});assert.equal(open(c.key,c.channel,'test-message-123456','phone',p).text,'不要创建会话');assert(!p.includes('不要'));for(const [ch,id,role]of [[c.channel,'other-message-123456','phone'],['other-channel-123456','test-message-123456','phone'],[c.channel,'test-message-123456','hub']])assert.throws(()=>open(c.key,ch,id,role,p));});
test('duplicate network messages dispatch once and only exact native turn replies',async()=>{const h=harness(),id=crypto.randomUUID();h.incoming(id,{type:'text',text:'不要创建会话，只回复进展'});h.remote.push({...h.remote[0],seq:2});await h.channel.tick();assert.equal(h.calls.length,1);assert.equal(h.s.inbox.length,1);assert.equal(h.s.inbox[0].turnId,'exact-turn');h.assistant.readLiveFinal=()=>({records:[{turnId:'other-turn',text:'旧回复'}]});await h.channel.tick();assert(!h.s.outbox.some(r=>r.id==='answer-'+id));h.assistant.readLiveFinal=()=>({records:[{turnId:'exact-turn',text:'本轮回复'}]});await h.channel.tick();assert.equal(h.s.inbox[0].state,'answered');assert.equal(h.s.outbox.filter(r=>r.id==='answer-'+id).length,1);await h.channel.tick();assert.equal(h.calls.length,1);});
test('uncertain submission is not automatically retried and late exact receipt recovers',async()=>{const h=harness(),id=crypto.randomUUID();h.assistant.send=async r=>{h.calls.push(r);throw Error('interrupted')};h.incoming(id,{type:'text',text:'继续推进'});await h.channel.tick();await h.channel.tick();assert.equal(h.calls.length,1);assert.equal(h.s.inbox[0].state,'unknown');h.channel.observeReceipt({status:'confirmed',turnId:'recovered',clientSubmissionId:id,sessionId:'wrong'});assert.equal(h.s.inbox[0].state,'unknown');h.channel.observeReceipt({status:'confirmed',turnId:'recovered',clientSubmissionId:id,sessionId:'fixed-assistant'});assert.equal(h.s.inbox[0].state,'waiting');});
test('voice returns editable transcript and cannot dispatch a task without user confirmation',async()=>{const h=harness();h.incoming(crypto.randomUUID(),{type:'voice',pcm:'AQI='});await h.channel.tick();assert.equal(h.calls.length,0);const row=h.s.outbox.find(r=>r.id.startsWith('transcript-'));assert.equal(open(h.c.key,h.c.channel,row.id,'hub',row.payload).text,'识别内容');assert.equal(h.s.inbox[0].state,'transcribed');});
test('busy assistant leaves requests queued; other backend refuses explicitly',async()=>{const h=harness();h.assistant.overview=()=>({status:'running'});h.incoming(crypto.randomUUID(),{type:'text',text:'查进展'});await h.channel.tick();assert.equal(h.calls.length,0);h.assistant.overview=()=>({status:'idle'});h.assistant.ensureSession=async()=>({ok:true,sessionId:'claude',backendKind:'claude'});await h.channel.tick();assert.equal(h.calls.length,0);assert.equal(h.s.inbox[0].state,'rejected');});
test('pause during network wait cannot start a new delegated task',async()=>{const h=harness();h.incoming(crypto.randomUUID(),{type:'text',text:'创建任务'});const request=h.channel.request;h.channel.request=async(...args)=>{const r=await request(...args);h.s.enabled=false;return r};await h.channel.tick();assert.equal(h.calls.length,0);});
test('watch notification identity is safe and bounded on relay protocol',async()=>{const h=harness();h.assistant.notifications=()=>({notifications:[{id:'a'.repeat(70)+':'+crypto.randomUUID(),createdAt:2,title:'任务',text:'新回复'}]});await h.channel.tick();assert.equal(h.s.notices.length,1);assert(h.s.outbox.every(r=>/^[A-Za-z0-9_-]{16,80}$/.test(r.id)));});
test('definitively not sent startup failure rejects without blocking subsequent tasks',async()=>{const h=harness();h.assistant.send=async()=>({ok:false,receipt:{ok:false,notSent:true,error:'cli-not-ready',message:'启动尚未完成'}});h.incoming(crypto.randomUUID(),{type:'text',text:'查进展'});await h.channel.tick();assert.equal(h.s.inbox[0].state,'rejected');assert(h.s.outbox.some(r=>r.id.startsWith('rejected-')));h.assistant.send=async r=>{h.calls.push(r);return{receipt:{receipt:{status:'confirmed',turnId:'new'}}}};h.remote.push({seq:2,id:crypto.randomUUID(),payload:''});h.remote.length=0;const id=crypto.randomUUID();h.remote.push({seq:2,id,payload:seal(h.c.key,h.c.channel,id,'phone',{type:'text',text:'再查进展'})});await h.channel.tick();assert.equal(h.calls.length,1);assert.equal(h.s.inbox[1].state,'waiting');});
