'use strict';
const assert = require('node:assert/strict');
const { noticeContent } = require('../renderer/ui-feedback');
const { effortLabel, speedLabel } = require('../renderer/ui-labels');
const occupied = noticeContent('会话恢复失败：thread private-id already has an active writer');
assert.equal(occupied.title, '这个会话正在另一窗口中使用');
assert.match(occupied.detail, /private-id/);
assert.doesNotMatch(occupied.body, /private-id/);
assert.equal(noticeContent('原始错误 <script>不可丢失</script>').body, '原始错误 <script>不可丢失</script>');
assert.equal(effortLabel('high'), '高');
assert.equal(effortLabel('future-tier'), 'future-tier');
assert.equal(speedLabel('standard'), '标准');
console.log('PASS UI presentation: lossless error detail and parameter labels');
