'use strict';
const assert = require('node:assert/strict');
const { renderMessageBody } = require(process.env.HUB_MESSAGE_VIEW || '../renderer/conversation-message-view');
const { marked } = require('marked');
const raw = require('./fixtures/collapsed-markdown');
const escapeHtml = text => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
let calls = 0;
const renderMarkdown = text => { calls++; return marked.parse(text).replace(/<script>[\s\S]*?<\/script>/g, ''); };
const html = renderMessageBody(raw, { escapeHtml, renderMarkdown });
const preview = html.slice(html.indexOf('class="conversation-long-preview"')).split('</summary>')[0];
assert.match(preview, /<strong>折叠也要看清重点/);
assert.match(preview, /<ul>/);
assert.match(preview, /<table>/);
assert.match(preview, /<pre><code class="language-javascript">/);
assert.match(preview, /href="https:\/\/example.com\/guide"/);
assert(!preview.includes('<script>'));
assert.equal(calls, 1, 'reuse the same safe renderer output, without a second parse or cut Markdown');
assert.equal((html.match(/END-OF-MARKDOWN-ANSWER/g) || []).length, 2, 'complete answer and visual preview both preserve source');
const user = renderMessageBody(raw, { escapeHtml, renderMarkdown, isUser: true });
assert.equal(calls, 1, 'user prompts stay literal');
assert(user.includes('&lt;script&gt;') && !user.includes('<strong>'));
assert.equal(renderMessageBody('**短消息**', { escapeHtml, renderMarkdown }), '<p><strong>短消息</strong></p>\n');
console.log('PASS: collapsed Markdown blocks, complete delimiters, one safe render, literal user input, short messages');
