'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { createDesktopOrganizer } = require('../core/desktop-organizer');
(async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'hub-desktop-unit-'));
  const desktop = path.join(root, 'Desktop'); await fs.mkdir(desktop);
  await fs.writeFile(path.join(desktop, 'report.pptx'), 'original');
  await fs.writeFile(path.join(desktop, 'AI Hub.lnk'), 'link');
  await fs.writeFile(path.join(desktop, 'desktop.ini'), 'system');
  await fs.mkdir(path.join(desktop, 'claude-artifacts')); await fs.writeFile(path.join(desktop, 'claude-artifacts', 'old.html'), 'old report');
  const service = createDesktopOrganizer({ testRoot: root });
  const plan = await service.scan();
  assert.equal(plan.items.length, 3); assert.equal(plan.items.filter(row => row.selected).length, 2);
  await assert.rejects(service.execute({ id: 'bad', keys: [] }), /过期/);
  const result = await service.execute({ id: plan.id, keys: plan.items.filter(row => row.selected).map(row => row.key) });
  assert.equal(result.moved, 2);
  assert.equal(await fs.readFile(path.join(desktop, 'AI Hub.lnk'), 'utf8'), 'link');
  assert.equal(await fs.readFile(result.rows.find(row => row.name === 'report.pptx').target, 'utf8'), 'original');
  await fs.writeFile(path.join(desktop, 'report.pptx'), 'new file');
  const undo = await service.undo(); assert.equal(undo.restored, 1);
  assert.equal(await fs.readFile(path.join(desktop, 'report.pptx'), 'utf8'), 'new file');
  assert.match(undo.rows.find(row => row.name === 'report.pptx').error, /已存在/);
  await fs.unlink(path.join(desktop, 'report.pptx'));
  assert.equal((await service.undo()).restored, 1);
  assert.equal(await fs.readFile(path.join(desktop, 'report.pptx'), 'utf8'), 'original');
  const changed = await service.scan(); await fs.writeFile(path.join(desktop, 'report.pptx'), 'changed file');
  const skipped = await service.execute({ id: changed.id, keys: [changed.items.find(row => row.name === 'report.pptx').key] });
  assert.equal(skipped.moved, 0); assert.match(skipped.rows[0].error, /有变化/);
  const again = await service.scan();
  await fs.mkdir(path.join(service.archive, '.organizer-lock'));
  await assert.rejects(service.execute({ id: again.id, keys: [again.items[0].key] }), /占用/);
  await fs.rmdir(path.join(service.archive, '.organizer-lock'));
  console.log('PASS desktop archive, legacy artifacts, launcher preservation, conflict-safe undo, changed-file and cross-instance lock');
})().catch(error => { console.error(error); process.exitCode = 1; });
