'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const { verifyColumns, createDesktopIconLayout, desktopLayoutScript } = require('../core/desktop-icon-layout');
const { registerDesktopOrganizerIpc } = require('../main/ipc/desktop-organizer-handlers');
const sample = { flags: 0x801, spacingX: 90, spacingY: 100, icons: Array.from({ length: 8 }, (_, index) => ({ index, x: Math.floor(index / 6) * 90, y: index % 6 * 100 })) };
(async () => {
  assert.equal(desktopLayoutScript(path.join('dev', 'core'), 'resources'), path.join('dev', 'scripts', 'desktop-icon-layout.ps1'));
  assert.equal(desktopLayoutScript(path.join('resources', 'app.asar', 'core'), 'resources'), path.join('resources', 'scripts', 'desktop-icon-layout.ps1'));
  assert.deepEqual(verifyColumns(sample), { iconCount: 8, columns: 2, rowsPerColumn: 6, verified: true });
  assert.throws(() => verifyColumns({ ...sample, flags: 0x800 }), /未启用/);
  const gaps = structuredClone(sample); gaps.icons[2].y += 100; assert.throws(() => verifyColumns(gaps), /空隙/);
  const horizontal = structuredClone(sample); horizontal.icons[1].x += 90; assert.throws(() => verifyColumns(horizontal), /顺序/);
  const native = createDesktopIconLayout({ platform: 'win32', run: async (_exe, _args, options) => { assert.equal(options.windowsHide, true); return { stdout: JSON.stringify({ ok: true, after: sample }) }; } });
  assert.equal((await native.arrange()).simulated, false);
  await assert.rejects(createDesktopIconLayout({ platform: 'win32', run: async () => { const error = new Error('exit 1'); error.stdout = JSON.stringify({ ok: false, error: 'Explorer unavailable' }); throw error; } }).arrange(), /Explorer unavailable/);
  await assert.rejects(createDesktopIconLayout({ platform: 'win32', run: async () => ({ stdout: 'invalid response' }) }).arrange(), /可核对/);
  await assert.rejects(createDesktopIconLayout({ platform: 'linux' }).arrange(), /仅支持 Windows/);
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'hub-icon-layout-unit-'));
  const fixture = path.join(root, 'fixture'); await fs.mkdir(path.join(fixture, 'Desktop'), { recursive: true });
  await fs.writeFile(path.join(fixture, 'Desktop', 'report.txt'), 'original');
  process.env.HUB_DESKTOP_ORGANIZER_TEST_ROOT = fixture; process.env.CLAUDE_HUB_E2E = '1';
  const handlers = new Map();
  registerDesktopOrganizerIpc({ handle: (channel, fn) => handlers.set(channel, fn) }, { dataDir: path.join(root, 'hub-data'), layoutService: { arrange: async () => { throw new Error('test layout failure'); } } });
  const plan = await handlers.get('desktop-organizer:scan')({}, {});
  const result = await handlers.get('desktop-organizer:execute')({}, { id: plan.id, keys: plan.items.map(item => item.key) });
  assert.equal(result.moved, 1); assert.equal(result.ok, true); assert.equal(result.layout.ok, false); assert.match(result.layout.error, /layout failure/);
  assert.equal(await fs.readFile(result.rows[0].target, 'utf8'), 'original');
  assert.equal((await handlers.get('desktop-organizer:arrange')({}, {})).ok, false);
  console.log('PASS vertical columns and wrap, gaps rejected, native errors surfaced, hidden helper, archive result preserved when layout fails');
})().catch(error => { console.error(error); process.exitCode = 1; });
