'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const Feed=require('../core/dev-workbench-feed');
const groupchat=require('../core/group-chat-orchestrator');
const {createLoopEngine}=require('../main/groupchat/loop-engine');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'dev-progress-message-'));
const orch=groupchat.getOrchestrator(root,'progress-task'),turn=orch.beginTurn('修紧凑布局');
const n=typeof turn==='number'?turn:orch.state.currentTurn;
orch.recordTurnPrompt(n,'s1','完整任务提示');
const now=Date.now();
assert.equal(orch.recordProgressUpdate('unrelated','另一席位',now,'未知'),false);
assert.equal(orch.recordProgressUpdate('s1','迟到的旧轮更新',1,'工作席'),false);
assert.equal(orch.recordProgressUpdate('s1','开始检查创建窗口',now,'工作席'),true);
assert.equal(orch.recordProgressUpdate('s1','开始检查创建窗口',now+1,'工作席'),false);
assert.equal(orch.state.turns.length,0,'Progress cannot complete a turn');
assert.equal(orch.state.devWorkbench.card,null,'Progress cannot supply final handoff');
assert.equal(orch.state.messages.find(m=>m.id===`p${n}-s1`).status,'progress_update');
const engine=createLoopEngine({meetingManager:{},getDispatcher:()=>({})});
assert.equal(engine.__test.hasProgressCard('UPDATE: 开始检查创建窗口'),false,'Process update cannot release the builder gate');
orch.completeTurn(n,'修紧凑布局',[{sid:'s1',text:'PROGRESS: 已改好\nVERIFIED: 7 项通过',status:'completed'}],{s1:{memberId:'m1',displayName:'工作席'}});
assert.equal(orch.state.devWorkbench.card.progress,'已改好');
assert.equal(orch.state.turns[0].by.s1,'PROGRESS: 已改好\nVERIFIED: 7 项通过');
assert.equal(orch.recordProgressUpdate('s1','结束后的重复更新',now+20,'工作席'),false,'Completed prompt no longer accepts updates');
assert.equal(Feed.processUpdate('```\nUPDATE: 伪造\n```\nUPDATE: 正文'),'正文');
assert.equal(Feed.processUpdate('PROGRESS: 最终汇报'),'');
console.log('live progress: PASS (turn fencing, deduplication, original message, no false handoff)');
