'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {SqliteSessionSearchIndex}=require('../core/session-search-sqlite-index');const {AssistantHistory}=require('../core/hub-assistant/history');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'assistant-history-')),file=path.join(dir,'search.sqlite');const index=new SqliteSessionSearchIndex(file);t.after(()=>index.close());return{index,history:new AssistantHistory(file)};}
function source(key,docs,extra={}){return{key,signature:key,searchable:true,session:{key,provider:'codex',title:key,updatedAt:100000,hubSessionId:'hub-'+key,nativeSessionId:'native-'+key,...extra},docs:docs.map((d,i)=>({eventId:'m'+i,scope:'assistant',text:'answer'+i,ordinal:i,timestamp:100000,...d}))};}
test('context omits tools, preview echoes, group transcript cards and the assistant native duplicate',t=>{const {index,history}=fixture(t);index.replaceSource(source('ordinary',[{scope:'user',text:'问题'},{text:'回答'},{scope:'tool',text:'工具结果'},{eventId:'last-output-preview',text:'预览回声'}]));index.replaceSource(source('meeting',[{text:'旧群聊卡片'}],{provider:'meeting'}));index.replaceSource(source('assistant',[{text:'助理自身'}],{hubSessionId:null,nativeSessionId:'assistant-native'}));const result=history.context({now:110000,hours:1,excludeNativeSessionId:'assistant-native'});assert.deepEqual(result.sources.map(s=>s.text).sort(),['回答','问题'].sort());});
test('keyword evidence surrounds its actual hit instead of the newest unrelated messages',t=>{const {index,history}=fixture(t);index.replaceSource(source('long-thread',Array.from({length:30},(_,i)=>({text:i===2?'独角鲸检索锚点':'其他自然对话'+i,timestamp:i<3?1000:100000}))));const result=history.context({query:'独角鲸检索锚点',now:100000,hours:1});assert.equal(result.range,'all-indexed-history');assert.equal('since' in result,false);assert.ok(result.sources.some(s=>s.text.includes('独角鲸检索锚点')));});
test('selected text obeys the budget and declares omitted context',t=>{const {index,history}=fixture(t);index.replaceSource(source('large',Array.from({length:20},()=>({text:'内容'.repeat(3000)}))));const result=history.context({now:110000,hours:1,maxChars:3000});assert.ok(result.selectedChars<=3000);assert.equal(result.truncated,true);assert.ok(result.sources[0].text.includes('[中段省略]'));});
test('calendar range excludes records beyond its end rather than using capture time',t=>{const {index,history}=fixture(t);index.replaceSource(source('range',[{text:'昨天结果',timestamp:50000},{text:'今天结果',timestamp:100000}]));const result=history.context({now:110000,from:40000,to:60000,rangeKind:'calendar-yesterday'});assert.deepEqual(result.sources.map(s=>s.text),['昨天结果']);assert.equal(result.until,60000);});
