'use strict';
async function openPhone({document,ipcRenderer}){
 if(document.querySelector('.assistant-phone-dialog'))return;
 const dialog=document.createElement('dialog');dialog.className='assistant-phone-dialog';dialog.style.cssText='max-width:520px;width:90%;padding:28px;border:1px solid #dedee2;border-radius:18px;background:#fff;color:#1d1d1f';
 dialog.innerHTML='<h2 style="margin-top:0">手机助理 · 1.0</h2><p>安卓 App 与电脑的同一个助理交流。文字、图片与语音录音通过加密连接传递。</p><p><a href="https://ai.lt-stockpartner.tech/assistant/android/" target="_blank" rel="noopener">下载安装安卓 App</a></p><p class="phone-state" role="status">正在读取状态…</p><textarea class="phone-code" readonly aria-label="手机连接码" style="display:none;width:100%;height:95px;font:12px/1.6 monospace;overflow-wrap:anywhere"></textarea><p class="phone-instruction" hidden>把连接码复制到手机 App 的“连接电脑”。连接码只交给你自己的手机；电脑需保持 Hub 开启，手机 1.0 使用 Codex 助理。</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button data-phone="pair">生成／显示连接码</button><button data-phone="pause">暂停连接</button><button data-phone="resume">恢复连接</button><button data-phone="close">关闭</button></div><p style="font-size:12px;color:#69746f">语音复用电脑现有的百炼语音设置。手机识别后先显示文字，由你确认再交给助理。</p>';
 const paint=r=>{dialog.querySelector('.phone-state').textContent=r.ok?(r.connected?'手机通道已连接':r.enabled?'正在连接手机服务…':'手机通道尚未开启')+(r.issue?' · '+r.issue:''):(r.error||'连接失败');if(r.code){const field=dialog.querySelector('.phone-code');field.style.display='block';field.value=r.code;dialog.querySelector('.phone-instruction').hidden=false;}};
 dialog.addEventListener('click',async e=>{const action=e.target.closest('[data-phone]')?.dataset.phone;if(!action)return;if(action==='close'){dialog.close();dialog.remove();return;}e.target.disabled=true;dialog.querySelector('.phone-state').textContent='正在处理…';try{paint(await ipcRenderer.invoke('assistant:phone-'+action));}finally{e.target.disabled=false;}});
 let timer=null;dialog.addEventListener('close',()=>{clearInterval(timer);dialog.remove();});document.body.append(dialog);dialog.showModal();paint(await ipcRenderer.invoke('assistant:phone-status'));if(dialog.open)timer=setInterval(async()=>{if(dialog.open)paint(await ipcRenderer.invoke('assistant:phone-status'));},3000);
}
module.exports={openPhone};
