'use strict';
const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {seal,open,credentials,invite}=require('./crypto');
class PhoneChannel{
 constructor({assistant,journal,renderCards,transcribe,imageRoots=[]}){Object.assign(this,{assistant,journal,renderCards,transcribe,imageRoots});this.closed=false;this.issue=null;this.online=false;}
 status(){const s=this.journal.state;return{ok:true,version:'1.0.0',enabled:s.enabled,connected:this.online,issue:this.issue,paired:!!s.credentials,pending:s.inbox.filter(r=>r.state==='queued').length,unknown:s.inbox.filter(r=>r.state==='unknown').length,voice:true,backend:'codex'};}
 async request(endpoint,{method='GET',body,role='hub'}={}){const c=this.journal.state.credentials;if(!c)throw Error('请先连接手机');const q=method==='GET'?`?channel=${c.channel}&role=${role}&after=${this.journal.state.cursor}`:'';const headers={Authorization:'Bearer '+c.hubToken,'Content-Type':'application/json'};if(endpoint==='/create'){const file='C:/VibeData/Secrets/aihub-phone-relay-registration.txt';const secret=process.env.HUB_PHONE_REGISTER_KEY||(fs.existsSync(file)?fs.readFileSync(file,'utf8').trim():'');if(!/^[A-Za-z0-9_-]{43}$/.test(secret))throw Error('手机连接服务尚未配置，请先完成手机服务部署');headers['X-Register-Key']=secret;}const r=await fetch(c.url+endpoint+q,{method,headers,body:body&&JSON.stringify({...body,channel:c.channel,role}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('手机连接服务暂时不可用（'+r.status+'）');return r.json();}
 async pair(){const s=this.journal.state;if(!s.credentials)this.journal.change(x=>{x.credentials=credentials();x.notices=this.assistant.notifications({limit:200}).notifications.map(n=>n.id);x.created=Date.now();});const {channel,hubToken,phoneToken}=s.credentials;await this.request('/create',{method:'POST',body:{channel,hubToken,phoneToken}});this.journal.change(x=>{x.enabled=true;});this.start();return{...this.status(),code:invite(s.credentials)};}
 emit(id,value){const s=this.journal.state;if(s.outbox.some(r=>r.id===id))return;const c=s.credentials;this.journal.change(x=>{x.outbox.push({id,payload:seal(c.key,c.channel,id,'hub',{...value,time:Date.now()}),sent:false});});}
 observeReceipt(r){if(r?.status!=='confirmed'||r.notSent||r.contentMismatch||!r.turnId)return;const row=this.journal.state.inbox.find(x=>x.id===r.clientSubmissionId&&x.sessionId===r.sessionId);if(row&&['dispatching','unknown','waiting'].includes(row.state)){this.journal.change(()=>{row.turnId=r.turnId;row.state='waiting';row.issue=null;});this.emit('receipt-'+row.id,{type:'status',requestId:row.id,state:'received',text:'助理已收到，正在处理。'});}}
 start(){if(this.timer||this.closed)return;this.timer=setInterval(()=>void this.tick(),2200);this.timer.unref();void this.tick();}
 async tick(){const s=this.journal.state;if(this.working||this.closed||!s.enabled||!s.credentials)return;this.working=true;
 try{const polled=await this.request('/poll');if(this.closed||!s.enabled)return;this.online=true;this.issue=null;
  for(const packet of polled.messages){if(packet.seq<=s.cursor)continue;if(!s.inbox.some(r=>r.id===packet.id)){try{const m=open(s.credentials.key,s.credentials.channel,packet.id,'phone',packet.payload);if(!['text','voice'].includes(m.type))throw Error('消息类型不支持');if(m.type==='text'&&(typeof m.text!=='string'||!m.text.trim()||m.text.length>50000))throw Error('任务文字无效');this.journal.change(x=>{x.inbox.push({...m,id:packet.id,state:'queued'});x.cursor=packet.seq;});}catch{this.journal.change(x=>{x.cursor=packet.seq;});this.emit('invalid-'+packet.id,{type:'status',requestId:packet.id,state:'rejected',text:'消息校验未通过，未提交任务。'});}}else this.journal.change(x=>{x.cursor=packet.seq;});}
  const active=s.inbox.find(r=>['dispatching','waiting','unknown'].includes(r.state));
  if(active?.turnId){const answer=this.assistant.readLiveFinal(active.sessionId).records.find(r=>r.turnId===active.turnId);if(answer){await this.reply('answer-'+active.id,answer.text,{requestId:active.id});this.journal.change(()=>{active.state='answered';});}}
  if(!s.inbox.some(r=>['dispatching','waiting','unknown'].includes(r.state))&&!this.assistant.switching){const row=s.inbox.find(r=>r.state==='queued');if(row){
    if(row.type==='voice'){this.journal.change(()=>{row.state='transcribing';});try{const text=await this.transcribe(row.pcm);if(!text.trim())throw Error('没有听清，请重新录音');this.emit('transcript-'+row.id,{type:'transcript',requestId:row.id,text});this.journal.change(()=>{row.state='transcribed';delete row.pcm;});}catch(e){this.emit('voiceerror-'+row.id,{type:'status',requestId:row.id,state:'rejected',text:e.message});this.journal.change(()=>{row.state='rejected';delete row.pcm;});}}
    else{const overview=this.assistant.overview();if(!overview.submissionPending&&!['running','waiting'].includes(overview.status)){const ready=await this.assistant.ensureSession();if(!ready.ok)throw Error(ready.error||'助理未就绪');if(ready.backendKind&&ready.backendKind!=='codex'){this.emit('backend-'+row.id,{type:'status',requestId:row.id,state:'rejected',text:'手机 1.0 请先在电脑助理中选择 Codex；不会替你切换模型。'});this.journal.change(()=>{row.state='rejected';});}else{this.journal.change(()=>{row.state='dispatching';row.sessionId=ready.sessionId;});try{const r=await this.assistant.send({text:row.text,requestId:row.id});const receipt=r.receipt?.receipt;if(receipt?.status==='confirmed'&&receipt.turnId)this.observeReceipt({...receipt,sessionId:ready.sessionId,clientSubmissionId:row.id});else if(row.state==='dispatching')this.journal.change(()=>{row.state='unknown';});}catch(e){this.journal.change(()=>{row.state='unknown';row.issue=e.message;});}if(row.state==='unknown')this.emit('unknown-'+row.id,{type:'status',requestId:row.id,state:'unknown',text:'任务是否送达尚未确认，正在核对，不会自动再发。'});}}}
   }}
  for(const n of this.assistant.notifications({limit:200}).notifications){if(s.notices.includes(n.id)||n.createdAt<s.created)continue;await this.reply('notice-'+crypto.createHash('sha256').update(n.id).digest('hex').slice(0,32),'关注任务「'+n.title+'」有新进展：\n'+n.text,{notice:true});this.journal.change(x=>x.notices.push(n.id));}
  for(const row of s.outbox.filter(r=>!r.sent).slice(0,4)){await this.request('/send',{method:'POST',body:{id:row.id,payload:row.payload}});this.journal.change(()=>{row.sent=true;});}
 }catch(e){this.online=false;this.issue=e.message;}finally{this.working=false;}}
 async reply(id,text,extra={}){this.emit(id,{type:'answer',text,...extra});for(const [i,img]of require('./images').answerImages(text,{roots:this.imageRoots}).entries())this.emit(id+'-original-'+i,{type:'image',originId:id,png:img.data.toString('base64'),caption:img.caption,...extra});if(this.journal.state.outbox.some(r=>r.id===id+'-image-0'))return;try{const images=await this.renderCards(text);images.forEach((b,i)=>this.emit(id+'-image-'+i,{type:'image',originId:id,png:b.toString('base64'),caption:'结果卡片',...extra}));}catch(e){this.emit(id+'-image-error',{type:'status',text:'文字结果已就绪，图片暂时生成失败。'});}}
 pause(){this.journal.change(s=>{s.enabled=false;});clearInterval(this.timer);this.timer=null;this.online=false;return this.status();}
 close(){this.closed=true;clearInterval(this.timer);}
}
module.exports={PhoneChannel};
